Update .github/workflows/build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -8,32 +8,43 @@ on:
 jobs:
   build-api-spec:
     runs-on: ubuntu-latest
-
     steps:
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.10'
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+      
       - name: Checkout main repository office-js-api-declarations
         uses: actions/checkout@v4
         with:
           path: office-js-api-declarations
-
-      - name: Checkout repository with examples office-js-api
-        uses: actions/checkout@v4
-        with:
-          path: office-js-api
+          ref: master
 
       - name: Checkout build_tools repository
         uses: actions/checkout@v4
         with:
           repository: ONLYOFFICE/build_tools
           token: ${{ secrets.READ_PAT }}
-          ref: release/v8.2.0
+          ref: master
           path: build_tools
+
+      - name: Checkout repository with examples office-js-api
+        uses: actions/checkout@v4
+        with:
+          repository: ONLYOFFICE/office-js-api
+          token: ${{ secrets.READ_PAT }}
+          ref: master
+          path: office-js-api
 
       - name: Checkout sdkjs repository
         uses: actions/checkout@v4
         with:
           repository: ONLYOFFICE/sdkjs
           token: ${{ secrets.READ_PAT }}
-          ref: release/v8.2.0
+          ref: master
           path: sdkjs
 
       - name: Checkout sdkjs-forms repository
@@ -41,58 +52,58 @@ jobs:
         with:
           repository: ONLYOFFICE/sdkjs-forms
           token: ${{ secrets.READ_PAT }}
-          ref: release/v8.2.0
+          ref: master
           path: sdkjs-forms
-      
-      - name: Check release branches
+
+      - name: Fetch all repos without tags
         run: |
-          git -C build_tools fetch --all
-          release_branches=$(git -C build_tools branch -r | grep -E '^ *origin/release/v.'); \
-          echo "${release_branches}"
+          git -C build_tools fetch --no-tags || echo "Failed to fetch in build_tools"
+          git -C office-js-api-declarations fetch --no-tags || echo "Failed to fetch in office-js-api-declarations"
+          git -C office-js-api fetch --no-tags || echo "Failed to fetch in office-js-api"
+          git -C sdkjs fetch --no-tags || echo "Failed to fetch in sdkjs"
+          git -C sdkjs-forms fetch --no-tags || echo "Failed to fetch in sdkjs-forms"
 
-      - name Check hotfix branches
+      - name: Set env
         run: |
-          hotfix_branches=$(git -C build_tools branch -r | grep -E '^ *origin/hotfix/v.'); \
-          echo "${hotfix_branches}"
-      
-      - name: Echo release
-        run: echo ${{ steps.check-branch.env.release }}
-      
-      - name: Echo hotfix
-        run: echo ${{ steps.check-branch.outputs.hotfix }}
-
-      - name: Set up Node.js
-        uses: actions/setup-node@v4
-
-      - name: Install Node.js dependencies
-        run: |
-          cd build_tools/scripts/sdkjs_common/jsdoc
-          npm install
-
-      - name: Set up Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.10'
-
-      - name: Run Python script to generate docs
-        run: |
-          cd build_tools/scripts/sdkjs_common/jsdoc
-          python generate_docs_json.py
-          python generate_docs_plugins_json.py
+          branches=$(git -C build_tools branch -r | grep -E 'origin/(release/v|hotfix/v)' | sed 's|origin/||; s/^ *//; s/ *$//' | paste -sd "," -)
+          echo "branches=$branches" >> $GITHUB_ENV
+          echo "$branches"
 
       - name: Set up Git
         run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
 
-      - name: Create Pull Request
+      - name: Generate docs for each branch
         run: |
-          #BRANCH_NAME="update-api-spec-${{ github.run_number }}"
-          #cd office-js-api-declarations
-          #git checkout -b $BRANCH_NAME
-          #git add .
-          #git commit -m "Add documentation update from GitHub Actions"
-          #git push origin $BRANCH_NAME
-          #gh pr create --title "Update documentation from GitHub Actions" --body "This PR includes updates to the documentation artifacts generated by the GitHub Actions workflow." --base ${{ github.ref_name }} --head $BRANCH_NAME
-        env:
-          GITHUB_TOKEN: ${{ secrets.READ_PAT }}
+          for branch in $(echo "$branches" | tr ',' '\n'); do
+            echo "-------------------------------------------"
+            echo "Branch: $branch"
+            git -C build_tools switch "$branch" || echo "Failed to switch $branch in build_tools"
+            if [ ! -d "build_tools/scripts/sdkjs_common/jsdoc" ]; then
+              echo "Directory for build does not exist. Skipping $branch branch."
+              continue
+            fi
+            
+            git -C office-js-api-declarations reset --hard HEAD || echo "Failed to reset in office-js-api-declarations"
+            git -C office-js-api-declarations switch "master" || echo "Failed to switch master in office-js-api-declarations"
+            git -C office-js-api-declarations switch "$branch" || git -C office-js-api-declarations switch -c "$branch" || echo "Failed to create $branch in office-js-api-declarations"
+
+            git -C office-js-api switch "$branch" || echo "Failed to switch $branch in office-js-api"
+            git -C sdkjs switch "$branch" || echo "Failed to switch $branch in sdkjs"
+            git -C sdkjs-forms switch "$branch" || echo "Failed to switch $branch in sdkjs-forms"
+
+            cd build_tools/scripts/sdkjs_common/jsdoc
+            npm install
+            python generate_docs_json.py
+            python generate_docs_plugins_json.py
+            cd ../../../../
+
+            if ! git -C office-js-api-declarations diff --exit-code; then
+              git -C office-js-api-declarations add .
+              git -C office-js-api-declarations commit -m "Add documentation update from GitHub Actions"
+              git -C office-js-api-declarations push origin $branch
+            else
+              echo "Nothing to commit in $branch in office-js-api-declarations"
+            fi
+          done
